### ISSUE TITLE
pppoe-ptm overhead values seem to be off

### ISSUE THREAD

**Issue by moeller0** [dtaht/tc-adv#13]
As written elsewhere, the following section of tc/q_cake.c seems to require more explanation:
```
} else if (strcmp(*argv, "pppoe-ptm") == 0) {
atm = 2;
overhead += 27;
```

This is somewhat unexpected. Could you explain how you reached 27? I believe that the following to be true:

PPPoE: 2 Byte PPP + 6 Byte PPPoE = 8 Byte
VDSL2 (see IEEE 802.3-2012 61.3 and Rec. ITU-T G.992.3 (04/2009) Annex N relevant for VDSL2):
VDSL2-PTM: 1 Byte Start of Frame (S), 1 Byte End of Frame (Ck), 2 Byte TC-CRC (PTM-FCS), = 1 + 1 + 2 = 4 Byte
included ethernet header parts: 4 Byte Frame Check Sequence (FCS) + 6 Byte (dest MAC) + 6 Byte (src MAC) + 2 Byte (ethertype) = 4 + 6 + 6 + 2 = 18 Byte

Total: 8 + 4 + 18 = 30 Byte

Now, all of this could be wrong, but could you please describe why 27 is a better match for what happens on a PPPoE-PTM link?

**Comment by dtaht** [comment]
Is this unresolved?

**Comment by chromi** [comment]
It seems to be corrected in the code.
