### ISSUE TITLE
Overhead and compensated overhead reporting seems a bit too terse

### ISSUE THREAD

**Issue by moeller0** [dtaht/tc-adv#16]
Maybe we could change:
```
	if (!atm && overhead == ethernet) {
		fprintf(f, "raw ");
	} else {
		if (atm == 1)
			fprintf(f, "atm ");
		else if (atm == 2)
			fprintf(f, "ptm ");
		else
			fprintf(f, "noatm ");

		fprintf(f, "overhead %d ", overhead);

		// This is actually the *amount* of automatic compensation, so
		// also report the actual number... keep it short
		if (ethernet) {
			 fprintf(f, "via-ethernet(%d) ", ethernet);
	}

```

to:
```
	if (!atm) {
		fprintf(f, "raw ");
	} else {
		if (atm == 1)
			fprintf(f, "atm ");
		else if (atm == 2)
			fprintf(f, "ptm ");
		else
			fprintf(f, "noatm ");
    }
    
    // unconditionally report the total accounted overhead
    // as well as the auto compensated for amount
    fprintf(f, "overhead %d ", overhead);
    fprintf(f, "(auto-compensated overhead: %d) ", ethernet);
    
    // This is actually the *amount* of automatic compensation
    if (ethernet) {
        fprintf(f, "via-ethernet ");
	}

```

So that total compensated overhead and automatically compensated overhead are reported unconditionally. For debugging this would help quite a lot...

Note via-ethernet then is redundant, but it might be oaky to keep it for backward compatibility with scripts parsing "tc -s" output...

**Comment by chromi** [comment]
I'm keen to keep that line of output in a form that can be copied and
pasted into the tc command line without editing.  I don't think those
changes preserve that property.

I'm currently without the use of the machine carrying my full git history,
hence the lack of code activity from my end.  Let me see if I can extract
it from the hard drive and at least bring things up to date.

- Jonathan Morton

**Comment by moeller0** [comment]
> I'm keen to keep that line of output in a form that can be copied and
pasted into the tc command line without editing.  I don't think those
changes preserve that property.

Mmmh, I see quite a nice feature actually, has this been documented somewhere? 
Then how about we add a new line with explicit information about the overhead like:

Requested overhead: X bytes; thereof auto-compensated (skb->hard_header_len): Y bytes; requested MPU: Z bytes

As it really seems unintuitive to our users to omit that information, especially for debugging.
Or we simply add a dummy "parsing rule" for the compensated overhead reporting part to tc, so it gets mercifully and explicitly ignored?
I also would argue that at least we could unconditionally report "overhead N" especially since the "overhead == ethernet" test triggers both when no overhead was specified and when the requested overhead ist equal to hard_header_len. In other words currently the output can be pasted into tc, but it does in now way guarantee to actually be identical to the invocation that caused the current state. May I suggest to actually store the actual invocation in a string that also gets displayed, that would also have the nice property to also display the used keywords explicitly. In that way we could show a) what the user requested via tc, and b) what cake expanded it to, then the paste property should be trivially fulfilled by a) while b) gives all the additional information helpful for debugging, no?

> I'm currently without the use of the machine carrying my full git history,
hence the lack of code activity from my end.  Let me see if I can extract
it from the hard drive and at least bring things up to date.

Mmmh, could you be convinced to use github to share your development repository somewhere, that would make that situation (lack of access to git history and current source) somewhat more unlikely?

Best Regards

**Comment by dtaht** [comment]
this done?

**Comment by chromi** [comment]
I'm pretty sure the reporting of these details has been expanded since then - so yes.
