### ISSUE TITLE
Negative deficit overflow

### ISSUE THREAD

**Issue by dave14305** [dtaht/tc-adv#27]
https://github.com/dtaht/tc-adv/blob/15cbec556bfa6083d7627a06ef35169a32ad235e/tc/q_cake.c#L656

https://github.com/dtaht/tc-adv/commit/15cbec556bfa6083d7627a06ef35169a32ad235e

I have observed overflowing deficit values and wondering if the commit above neglected to change the printf format from unsigned to signed?
```
# tc -s class show dev eth0
class cake 8005:42b parent 8005:
 (dropped 44, overlimits 0 requeues 0)
 backlog 10598b 7p requeues 0
  deficit 4294967060 count 16 dropping drop_next -4295.0s blue_prob 0
class cake 8005:4e5 parent 8005:
 (dropped 48, overlimits 0 requeues 0)
 backlog 6056b 4p requeues 0
  deficit 4294967226 count 17 dropping drop_next -4294.9s blue_prob 0
class cake 8005:7b2 parent 8005:
 (dropped 55, overlimits 0 requeues 0)
 backlog 4542b 3p requeues 0
  deficit 4294965931 count 21 dropping drop_next -4294.9s blue_prob 0

# tc -s class show dev ifb4eth0
class cake 8006:a1 parent 8006:
 (dropped 0, overlimits 0 requeues 0)
 backlog 0b 0p requeues 0
  deficit 4294966517 count 1 dropping drop_next 1.1s blue_prob 0
class cake 8006:fc parent 8006:
 (dropped 0, overlimits 0 requeues 0)
 backlog 0b 0p requeues 0
  deficit 1449 count 0 blue_prob 0
```

**Comment by tohojo** [comment]
dave14305 <notifications@github.com> writes:

> https://github.com/dtaht/tc-adv/blob/15cbec556bfa6083d7627a06ef35169a32ad235e/tc/q_cake.c#L656
>
> I have observed overflowing deficit values and wondering if the commit
> above neglected to change the printf format from unsigned to signed?

Yeah, that looks like a bug - nice catch! Could you please try changing
that %u to a %d and check that everything looks fine with that?

**Comment by dave14305** [comment]
Unfortunately I am running a pre-compiled firmware image from https://github.com/RMerl/asuswrt-merlin.ng which just added CAKE support yesterday. I don't have a personal build environment available at the moment.

EDIT: sent a PR to the firmware maintainer in case he wants to fix it. I suspect he'll pass wanting to wait for an upstream fix.
https://github.com/RMerl/asuswrt-merlin.ng/pull/710

**Comment by RMerl** [comment]
I`ll try to create a test build with the proposed fix later today, we'll see how it goes.

**Comment by tohojo** [comment]
Eric Sauvageau <notifications@github.com> writes:

> I`ll try to create a test build with the proposed fix later today,
> we'll see how it goes.

Awesome! You could also try output'ing the json format ( with -j ) and
see if the number looks right there?

**Comment by RMerl** [comment]
> Awesome! You could also try output'ing the json format ( with -j ) and see if the number looks right there?

Unfortunately for backward compatibility reasons (Broadcom and Asus both customize iproute2's code for their own needs), I simply backported q_cake.c on top of iproute2-4.3.0, so I have no json output capability.

**Comment by RMerl** [comment]
@dave14305 try with this tc build (for RT-AC86U), I applied your recommended fix to it:

https://1drv.ms/u/s!AuCcWdNeYuXMi1HKTPa0oWzmoe6d?e=TsYu2G

**Comment by dtaht** [comment]
cake in merlin? world domination is at hand. Does the nat mode work in cake?

**Comment by RMerl** [comment]
Both Broadcom`s flowcache and pktrunner need to be disabled, otherwise flow handling in Cake doesn't work as expected unfortunately.  From talks with Asus on the matter, Cake would need to directly interface using Broadcom APIs to be able to work alongside it.

Still early to evaluate how well it's working overall, I only finalized the initial implementation this weekend, I haven't seeded public test builds yet except to a handful of testers.  And I can't really test it in depth myself, my RT-AX88U CPU can't keep up with my 400 Mbps cable connection if I disable HW acceleration. :(

**Comment by dave14305** [comment]
> @dave14305 try with this tc build (for RT-AC86U), I applied your recommended fix to it:
> 
> https://1drv.ms/u/s!AuCcWdNeYuXMi1HKTPa0oWzmoe6d?e=TsYu2G

Deficit looks better, but drop_next is still wrong. 

```
class cake 8001:57a parent 8001: 
 (dropped 9, overlimits 0 requeues 0) 
 backlog 4542b 3p requeues 0 
  deficit -33 count 6 dropping drop_next -4294.9s blue_prob 0
```

**Comment by tohojo** [comment]
dave14305 <notifications@github.com> writes:

>> @dave14305 try with this tc build (for RT-AC86U), I applied your recommended fix to it:
>> 
>> https://1drv.ms/u/s!AuCcWdNeYuXMi1HKTPa0oWzmoe6d?e=TsYu2G
>
> Deficit looks better, but drop_next is still wrong. 
>
> ```
> class cake 8001:57a parent 8001: 
>  (dropped 9, overlimits 0 requeues 0) 
>  backlog 4542b 3p requeues 0 
>   deficit -33 count 6 dropping drop_next -4294.9s blue_prob 0
> ```

Ah yes, that needs this additional patch to q_cake.c:

diff --git a/tc/q_cake.c b/tc/q_cake.c
index 0764f2bd8d87..4ff6056a1ab0 100644
--- a/tc/q_cake.c
+++ b/tc/q_cake.c
@@ -688,7 +688,7 @@ static int cake_print_xstats(struct qdisc_util *qu, FILE *f,
 
                        if (drop_next < 0) {
                                print_string(PRINT_FP, NULL, " drop_next -%s",
-                                       sprint_time(drop_next, b1));
+                                       sprint_time(-drop_next, b1));
                        } else {
                                print_uint(PRINT_JSON, "drop_next", NULL,
                                        drop_next);

**Comment by RMerl** [comment]
@dave14305 here's another test build with this second change:

https://1drv.ms/u/s!AuCcWdNeYuXMgZo1dpHb00qMENysiA?e=9B9raf

**Comment by dave14305** [comment]
> @dave14305 here's another test build with this second change:
> 
> https://1drv.ms/u/s!AuCcWdNeYuXMgZo1dpHb00qMENysiA?e=9B9raf

Beautiful!
```
class cake 8001:719 parent 8001: 
 (dropped 27, overlimits 0 requeues 0) 
 backlog 4542b 3p requeues 0 
  deficit -1498 count 21 dropping drop_next -14.1ms blue_prob 0
```

**Comment by RMerl** [comment]
Excellent, feel free to update your existing PR on my repo when you get the chance.

**Comment by tohojo** [comment]
Awesome, thank you for testing! I'm going to submit this to upstream iproute2 - would you folks like to be credited (with reported-by and tested-by tags in the patch)? If so, I'll need names and email addresses to put in there, Github usernames are not enough for upstream...

**Comment by dave14305** [comment]
> Awesome, thank you for testing! I'm going to submit this to upstream iproute2 - would you folks like to be credited (with reported-by and tested-by tags in the patch)?

No, thank you. I appreciate your responsiveness!

**Comment by RMerl** [comment]
You two are the ones who did all the actual work, I just did two test compile for @dave14305 to test things out. :)

**Comment by tohojo** [comment]
dave14305 <notifications@github.com> writes:

>> Awesome, thank you for testing! I'm going to submit this to upstream
>> iproute2 - would you folks like to be credited (with reported-by and
>> tested-by tags in the patch)?
>
> No, thank you. I appreciate your responsiveness!

Alright, cool! You're welcome, and thank you for reporting :)

**Comment by dtaht** [comment]
thx all for getting on this. If there is ANY WAY AT ALL to work with broadcom to get access to their apis on this and future products, please put them in touch with us?

**Comment by dtaht** [comment]
Also in reading this, I see it configured as a leaf node, rather than using cake all by itself with the bandwidth parameter. Is that working?

tc qdisc add dev whatever root cake bandwidth 10Mbit ack-filter docsis # nat

for cablemodems. (ifb is bigger)

**Comment by dave14305** [comment]
> 
> 
> Also in reading this, I see it configured as a leaf node, rather than using cake all by itself with the bandwidth parameter. Is that working?
> 
> tc qdisc add dev whatever root cake bandwidth 10Mbit ack-filter docsis # nat
> 
> for cablemodems. (ifb is bigger)

The cake qdisc is at the root of the eth0 device (no HTB or anything else). This issue was related to showing the individual flow stats via `tc -s class show dev eth0`

**Comment by dtaht** [comment]
ah. thx. sorry I didn't read closer.

**Comment by RMerl** [comment]
> thx all for getting on this. If there is ANY WAY AT ALL to work with broadcom to get access to their apis on this and future products, please put them in touch with us?

Not that I'm aware of, sorry.  And even if you did get access to the necessary documentation, Broadcom are paranoid bastards who keep everything under NDA.  Asus is closing source access to almost anything in their firmware that needs to interface with the BCM API, beside very public API calls.  Makes my life hell at times.

Maybe someone among the kernel devs might have better luck at getting directly in touch with Broadcom on this?  I personally have no contact at all with BCM, all my contacts are at Asus's networking division.

**Comment by RMerl** [comment]
@dtaht for reference, here's the setup done on my development RT-AX86U, with a cable 400/50 Mbps connection:

```
#!/bin/sh
ULIF='eth0'
DLIF='eth0'
MIF='ifb4eth0'
ULBW='bandwidth 51200kbit'
DLBW='bandwidth 409600kbit'
OVERHEAD='overhead 38 mpu 84'
FRAMING=''

case "$1" in
start)
# Upload
        tc qdisc add dev $ULIF root cake nat diffserv3 $ULBW $OVERHEAD $FRAMING 2>/dev/null

# Download
        ip link add name $MIF type ifb 2>/dev/null
        tc qdisc add dev $DLIF handle ffff: ingress 2>/dev/null
        tc qdisc add dev $MIF root cake nat wash $DLBW besteffort $OVERHEAD $FRAMING 2>/dev/null
        ip link set $MIF up 2>/dev/null
        tc filter add dev $DLIF parent ffff: prio 10 matchall action mirred egress redirect dev $MIF 2>/dev/null

        ;;
stop)
        tc qdisc del dev $ULIF root 2>/dev/null
        tc qdisc del dev $DLIF ingress 2>/dev/null
        tc qdisc del dev $MIF root 2>/dev/null
        ip link set $MIF down 2>/dev/null
        ip link del dev $MIF 2>/dev/null
        ;;
*)
esac
```
$FRAMING will be empty, atm or ptm based on the preset selected by the user on the webui (I exposed the most common presets like docsis, pppoe-atm, etc... and I apply their overhead values as hardcoded within tc/q_cake.c.

**Comment by dtaht** [comment]
I think it is past time to take political action against the binary blob and private api issues. Over here is a draft of a blast against the FCC that I would like comment and eventually, signage, on.

https://docs.google.com/document/d/1T21on7g1MqQZoK91epUdxLYFGdtyLRgBat0VXoC9e3I/edit?usp=sharing

Some context:  https://cdn.vox-cdn.com/uploads/chorus_asset/file/22344741/2021_0304_Bipartisan_Broadband_Speed_Letter_FINAL__1___1_.pdf

**Comment by dtaht** [comment]
we really need to reverse the binary blob trend and it is past time to start taking political action. Really. Going heads down on that. Please find more engineers as pissed off about bufferbloat and open source abuse as I am?

**Comment by tohojo** [comment]
FYI the original issue described here is now fixed in upstream iproute2: https://git.kernel.org/pub/scm/network/iproute2/iproute2.git/commit/?id=60204c81e47dfdb1ef066c3cb2cfd0f3f19570df
